### PR TITLE
Add debug logging to telegram gateway

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/nextcloud/twofactor_gateway/issues/110#issuecomment-426290531.

@Dretech please test this build: 
[twofactor_gateway.tar.gz](https://github.com/nextcloud/twofactor_gateway/files/2446429/twofactor_gateway.tar.gz)

### CODE REVIEW

**Comment by Dretech** [comment]
I tried to install the new 2fa gateway, but my Nextcloud does not run well at this moment. I have to reinstall Nextcloud and then I am able to test the new 2fa gateway.

**Comment by Freekers** [comment]
I used this version to generate more logging, please check: https://github.com/nextcloud/twofactor_gateway/issues/110#issuecomment-429955454

**Comment by Dretech** [comment]
The build Christoph referred to on oct 4 2018 does not solve my problem. I still get the following message after entering my Telegram ID:

afbeelding

**Comment by ChristophWurst** [comment]
Let's this discuss in either one of the corresponding open tickets or new one. Obviously, the screenshot doesn't help here because all this PR/build was about is adding more log entries to `nextcloud.log`.

**Pull request merged**
