### PR TITLE
Migrate personal settings to Nextcloud 15 provider settings API

### PR DESCRIPTION
**Pull request by ChristophWurst**
bildschirmfoto von 2019-03-08 10-13-34

### CODE REVIEW

**Comment by ChristophWurst** [comment]
cc @fblackburn1 @j-ed @kimsyversen @Dretech @noplanman for review :)

**Comment by fblackburn1** [comment]
I can't really review code as I am not a php/js developer
But after compiling and testing, I got the same result as your screenshot.
I test disable/enable my _Message gateway verification_ and everything works

Tested on nextcloud 15.0.4

+1

**Comment by kimsyversen** [comment]
Hello!

I have tested 2FA SMS with Puzzel and it works 👍

**Comment by ChristophWurst** [comment]
Thanks for testing :v:

**Comment by Dretech** [comment]
I tried to test Telegram, but my security screen does not display the 2FA providers.
Nextcloud security settings printscreen

**Comment by ChristophWurst** [comment]
This is a personal setting, not a admin setting.

**Comment by Dretech** [comment]
Thank you. Now I can see the security screen.
Unfortunately my Telegram ID I entered in the text box, gives the message "Could not verify your code. Please try again." I also tried my phone number, but I get the same error message.

**Comment by ChristophWurst** [comment]
Okay, that is a different issue. None of the configuration logic changed. It's the same as before, but on a different position. Please file a ticket for that issue!

**Pull request merged**
