### PR TITLE
Add NC 21/22 and PHP 8 support

### LINKED ISSUE #425: Nextcloud 21 incompatibility
My nextcloud decided to upgrade to 21.
This extension is marked as incompatible.

Tried to enable it anyway.

Result: Nextcloud stopped completely working. Even OCC command broke with this output:
```
root@nextcloud:~# nextcloud_occ app:list
An unhandled exception has been thrown:
Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /var/www/nextcloud/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /var/www/nextcloud/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/Client.php(66): GuzzleHttp\HandlerStack::create()
#2 /var/www/nextcloud/lib/private/Http/Client/ClientService.php(62): GuzzleHttp\Client->__construct()
#3 /var/www/nextcloud/lib/private/OCS/DiscoveryService.php(55): OC\Http\Client\ClientService->newClient()
#4 /var/www/nextcloud/lib/private/Server.php(1251): OC\OCS\DiscoveryService->__construct()
#5 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#6 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#8 /var/www/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query()
#9 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(434): OC\ServerContainer->query()
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#11 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map()
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#15 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#16 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#18 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map()
#20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#22 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#23 /var/www/nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#24 /var/www/nextcloud/lib/private/Console/Application.php(221): OC\ServerContainer->query()
#25 /var/www/nextcloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml()
#26 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#27 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
```

Solution was to move temporarily away the /var/www/nextcloud/apps/twofactor_gateway/ folder. Then Nextcloud worked again (and I could disable the app by settings page)

### LINKED ISSUE #426: PHP 8 Support
Related to #425 php8 support was introduced in v21.  Thanks

### PR DESCRIPTION
**Pull request by seyfahni**
This PR is based on #438, but addresses some additional issues:
- Cleaned up composer dependencies, so that `composer update` works with all PHP versions from 7.2 up to 8.0
- Cleaned up and fixed TravisCI builds (but for travis-ci.com, so the project can migrate)
- Added files to `.nextcloudignore` that shouldn't be part of releases
- Updated non-breaking node.js dependencies (closing some vulnerabilities too)
- Fixed php-cs findings

Replaces #438.
Fixes #426 and fixes #425.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Top notch pull request. I have no remarks. Awesome work, Niklas!

**Comment by seyfahni** [comment]
Thanks! Though I can't fix the missing signoffs for @boppy's commits.

**Comment by tetebueno** [comment]
@boppy

**Comment by boppy** [comment]
> Thanks! Though I can't fix the missing signoffs for @boppy's commits.

Signed, rebased, force-pushed.

**Comment by seyfahni** [comment]
> Signed, rebased, force-pushed.

With missing signoff I didn't mean a missing GPG signing of a commit, but the missing usage of `--signoff` when committing. It adds an additional line at the bottom of your commit message similar to:
```
Signed-off-by: Niklas Seyfarth <niklas@seyfarth.de>
```

It's what the DCO check (the one that is failing) is for: https://github.com/apps/dco

**Comment by seyfahni** [comment]
> Signed, rebased, force-pushed.

Thank you very much! Now all checks should pass.

Anyone that saw my previous (deleted) comment: I was super confused that boppy's signoff fix was in a branch in side of this repository and couldn't find it at first.

**Comment by boppy** [comment]
> Anyone that saw my previous (deleted) comment: I was super confused that boppy's signoff fix was in a branch in side of this repository and couldn't find it at first.

Yes, I also searched for the commit, because it was my first time fixing the signoff as mentioned in github's sign-off info-page. Always nice to encounter new functionality ;)

**Comment by mhzawadi** [comment]
Hello, any news on a merge for this?
As NC 22 is due soon

**Pull request merged**
