### PR TITLE
Clickatell.com API (SMS Platform)

### PR DESCRIPTION
**Pull request by killerbees19**
- [x] Successfully tested at Sandbox environment by @killerbees19 (_Test integration_)
- [x] Successfully tested at Production environment by @weesenxt (_Active integration_)

Reference: #359

### CODE REVIEW

**Comment by killerbees19** [comment]
- [x] Successfully tested at Sandbox environment (_Test integration_)
- [ ] Still not tested at Production environment (_Active integration_)

**Comment by killerbees19** [comment]
Ready for review 😎

(I think #359 should be closed after merge.)

**Comment by killerbees19** [comment]
\*push\* 😁

**Comment by vitormattos** [comment]
@killerbees19 can you fix the DCO?
https://github.com/nextcloud/twofactor_gateway/pull/360/checks?check_run_id=7055530924

**Comment by killerbees19** [comment]
@vitormattos Should be fixed now?

(Sorry for multiple forced pushes, I got a little bit lost in the meantime.)

**Comment by killerbees19** [comment]
> At the end, when all tests pass, will be good to squash all commits in only one commit, this will make the pull request more clean and will remove the tests/refactors commits did during the implementation process.

You mean something like `git rebase -i` with all my commits from this PR selected, but **without** the "merge master" commit?

**Comment by vitormattos** [comment]
Good! Lint stays happy again :D
To finish, can you squash all commits?

**Comment by killerbees19** [comment]
> Suggestion to organize all resuming what I would do:

Thanks, sounds good. I'll try it :-)

**Comment by killerbees19** [comment]
Looks good, no real difference between `feature/clickatell-2-bkp3` and `feature/clickatell-2` branches. 🤓

@vitormattos Ok?

**Comment by vitormattos** [comment]
Excelent work @killerbees19 !

**Pull request merged**
