### PR TITLE
Release v0.12.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
[Release checklist](https://blog.wuc.me/2018/08/14/nextcloud-app-release-process.html):
- [x] Created release branch.
- [x] Updated version number.
  - [x] Updated `appinfo/info.xml`.
  - [x] Updated `package.json` and ran `npm install`.
- [x] Beta1: [twofactor_gateway.tar.gz](https://github.com/nextcloud/twofactor_gateway/files/2851196/twofactor_gateway.tar.gz)
- [ ] Updated the changelog.
- [ ] Created release tag.
- [ ] Pushed tag to GitHub.
- [ ] Built package with `krankerl package`.
- [ ] Created new GitHub release.
- [ ] Published app on App Store.

cc @fblackburn1 @FabianZihlmann @j-ed @morph027 please test :)

Beta1

### CODE REVIEW

**Comment by morph027** [comment]
Works :+1:  Any new features i should keep an extra eye on?

**Comment by ChristophWurst** [comment]
Thanks for the quick feedback! I guess you tested the Signal integration. That is more than enough. We can't test all the different SMS gateways anyway because they are quite specific and I don't have access to any of these.

**Comment by morph027** [comment]
Jip, tested Signal. Enabled, confirmed and disabled.

**Comment by j-ed** [comment]
I've updated the files on my server and reactivated the app. A 2FA authentication was possible via Telegram afterwards. (I hope it's ok, that I haven't fully reconfigured the app).

**Comment by fblackburn1** [comment]
Everything works for the voip.ms plugin with the Beta1 build :+1: 

Tested on Nextcloud 15.0.4 with docker and MariaDB

**Comment by ChristophWurst** [comment]
Thanks for testing everyone :v:

**Pull request merged**
