### PR TITLE
WIP: Email as a 2nd factor.

### PR DESCRIPTION
**Pull request by Flow86**
Hi, 
since I didn't find a working email two factor solution, I've "hacked" it into this app.

Some caveats/TODOs:
- I don't know how to pre set the users email address as identifier, so the user can specify a different one than the users email address.
- Also the user has to manually enable email 2nd factor (could/should be automatically on if 2nd factor is forced?)
- There are no unittests yet
- The email interface IMailer is hardcoded
- A email template should be used to allow translations

Perhaps someone helps this code to add a proper implementation?

### CODE REVIEW

**Comment by ChristophWurst** [comment]
[Hmmmmmm :thinking: :see_no_evil: ](https://github.com/rullzer/twofactor_email)

**Comment by Flow86** [comment]
yes there is a two factor email plugin, but it does not work at all

**Comment by ChristophWurst** [comment]
Yes, I'm aware of that. But IMO it's better to finish the twofactor_email than hack email into this app. I don't really think email fits into this app, neither from a technical nor from a user's perspective. The description used is tailored to message gateways and not e-mails, hence can be confusing for users. And the configuration part is also different as you don't need to enter any identifier for email 2FA because Nextcloud already knows your email address.

Does that make sense?

**Comment by Flow86** [comment]
Yes you're completly right. Thats why I said "hacked". 

Of course the best would be to adapt https://github.com/rullzer/twofactor_email .

I did it in here since it was the best/working infrastructure code I've found ;-)

If I am honest, I only created this Pull Request to get attention on the "dead" twofactor_email - and that some want to use it (like me) also in the up to date version of nextcloud (which is not possible atm)

**Comment by ChristophWurst** [comment]
> I did it in here since it was the best/working infrastructure code I've found ;-)

That is great to hear! Many people have contributed to this repo to make it awesome :)

> If I am honest, I only created this Pull Request to get attention on the "dead" twofactor_email - and that some want to use it (like me) also in the up to date version of nextcloud (which is not possible atm)

You were successful, I guess :stuck_out_tongue:. We are aware that some people are interested in that app, but as it's not an official app of Nextcloud (the company) we have to rely on community help for the development. So just let us know if you would like to work on that app. It should be possible to get it up and running for recent Nextcloud versions with a few modifications. And I'm sure @rullzer will accept all PRs submitted.

**Comment by Flow86** [comment]
If I find the time, I will try my best to put effort into twofactor_email, so this will be obsolete then.

Are there any plans to make the twofactor_email app an official app? ;-)

**Comment by ChristophWurst** [comment]
> Are there any plans to make the twofactor_email app an official app? ;-)

No, there are none at the moment as there is no Enterprise interest right now and in general e-mail isn't really trustworthy as a channel for 2FA codes.

**Comment by Flow86** [comment]
I created a pull request for the other app now: https://github.com/rullzer/twofactor_email/pull/5

**Pull request closed without merging**
