### PR TITLE
Release v0.14.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
[Release checklist](https://blog.wuc.me/2018/08/14/nextcloud-app-release-process.html):
- [x] Created release branch.
- [x] Updated version number.
  - [x] Updated `appinfo/info.xml`.
  - [x] Updated `package.json` and ran `npm install`.
- [x] Updated the changelog.
- [x] RC1: [twofactor_gateway.tar.gz](https://github.com/nextcloud/twofactor_gateway/files/3176282/twofactor_gateway.tar.gz)
- [ ] Created release tag.
- [ ] Pushed tag to GitHub.
- [ ] Built package with `krankerl package`.
- [ ] Created new GitHub release.
- [ ] Published app on App Store.

@FabianZihlmann @j-ed @morph027 @fblackburn1 @MaKess @mmartinortiz @binford6000 @parreitu @Dretech @DieserMerlin @Freekers @djpremier  please review & test :)

### CODE REVIEW

**Comment by Dretech** [comment]
I tried to overwrite my existing configuration. But the new app is every time disabled. I tried to add my Telegram bot token, but I wonder if that will cause the disabled state of the twofactor_gateway app.

**Comment by parreitu** [comment]
In order to enable the twofactor_gateway APP you need to upgrade your Nextcloud to 16 version. 

Which is your version ?

I've upgraded Nextcloud and now I'm able to use the APP without problems !!

**Comment by Dretech** [comment]
Tanks for your reply.

I upgraded my Nextcloud installation to version 16.0
Did you install the twofactor gateway on version 15 and upgraded it in version 16?

**Comment by parreitu** [comment]
- First of all, I downloaded the code to the APPS folder replacing the stable version with the the RC published by @ChristophWurst  
- Then I realized that I need to upgrade Nextcloud to the last stable version (16), so I did it
- Finally I enabled the APP and enter my chatid code in the box. I had no problems to receive the Telegram code.

**Comment by Dretech** [comment]
@parreitu the twofactor_gateway is working in the way you described!

I assume that a new setup (admin config on command prompt) is not working with this version of twofactor_gateway.

**Comment by ChristophWurst** [comment]
> I assume that a new setup (admin config on command prompt) is not working with this version of twofactor_gateway

That should still work. The admin config only sets up the bot. The user config sets up the user/chat ID.

**Pull request merged**
